### ISSUE TITLE
Imgur Images

### ISSUE THREAD

**Issue by nnsdev** [CSNades/website#5]
Grab images from imgur and display them on the website.

**Comment by nnsdev** [comment]
I talked with @FatBoyXPC already about this. The plan was to display some small ads on the page so we can pay this website. The ImGur API only allows us to use their API when this page is NOT commercial and doesn't have ads. We have to thing about that.

**Comment by nnsdev** [comment]
@jung3o : 

@nownewstart It's just listed on here as a feature. I already know about that.

**Comment by nnsdev** [comment]
Oh okay :)

**Comment by FatBoyXPC** [comment]
Closing since #10 will cover this.
